### ISSUE TITLE
Feature Request: add http as default prefix or allow Links without prefix

### ISSUE THREAD

**Issue by sandronidi** [LeeO86/Bookmark-Page#16]
wenn ein link ohne "http://" als Link eingefügt wird kommt eine Fehlermeldung. Bitte entweder eine auto Vervollständigung einpflegen, welche http:// als Standard einsetzt. Alternativ kann auch erlaubt werden ohne Präfix zu speichern.

**Comment by LeeO86** [comment]
@sandronidi Ich habe 'http://' als default hinzugefügt, ist das ok so?

**Comment by sandronidi** [comment]
Passt für mich. Danke.
