### ISSUE TITLE
Feature Request: Ability to chose if a new tab or new windows should be opened

### ISSUE THREAD

**Issue by sandronidi** [LeeO86/Bookmark-Page#21]
Ein gutes Feature wäre, wenn bei der Konfiguration der Bookmarks die Möglichkeit besteht, auszuwählen ob beim Aufruf ein neuer Tab oder ein neues Fenster geöffnet werden sollte.

**Comment by LeeO86** [comment]
Ist nun mit der ShiftTaste gelöst. Da dies jedoch Browser spezifisch ist, funktioniert dies evtl nicht überall.
Darum habe ich dies nicht mit einem BookmarkSetting gelöst.
