### ISSUE TITLE
Feature Request: Themes

### ISSUE THREAD

**Issue by sandronidi** [LeeO86/Bookmark-Page#22]
Eine Unterscheidung zwischen verschiedenen Bookmark-page Instanzen wäre deutlicher, wenn man verschiedene Themes einsetzen könnte. Dies kann mit einem einfach light/dark mode umschalter implementiert werden ,ein Dropdown von verschiedenen vordefinierten Themes sein, oder die Möglichkeit die Hauptfarben mit HEX Codes selbst festzulegen.

**Comment by LeeO86** [comment]
Ich habe mal folgende Werte als Themes eingefügt:

Farbe | HSV Grad | body BG | nav BG
----- | -------- | ------- | ------
Red | 0 | #663333 | #402020
Yellow | 60 | #666633 | #404020
Pink | 300 | #663366 | #402040
Green | 120 | #336633 | #204020
Cyan | 180 | #336666 | #204040
Blue | 240 | #333366 | #202040
Grey | 208 | #6c757d | #343a40

OK so oder hast du bessere Farben?

**Comment by LeeO86** [comment]
Is accepted as is
