### ISSUE TITLE
bug: edit mode create new bookmark

### ISSUE THREAD

**Issue by sandronidi** [LeeO86/Bookmark-Page#5]
Wenn ein Bookmark zu editieren ausgewählt wird, wird statt das bestehende Element geändert, ein neues Element erstellt.

**Comment by LeeO86** [comment]
Kann ich bei mir nicht reproduzieren.
Musst du mir zeigen...

**Comment by sandronidi** [comment]
Wir haben festgestellt, dass das Problem nicht immer auftritt. Sobald das Problem genauer lokalisiert ist werde ich noch einmal einen Kommentar erfassen.

**Comment by LeeO86** [comment]
@sandronidi Falls der Bug nicht mehr auftritt mache ich den Issue zu...

**Comment by sandronidi** [comment]
Ich habe den Fehler nie mehr festgestellt.
